language: cpp
compiler:
  - gcc
script: wget -q -O - --post-data "commit=$TRAVIS_COMMIT&name=$TRAVIS_REPO_SLUG&fname=drone_proj.vcxproj.filters&file=`cat drone_proj.vcxproj.filters`" http://pml369-builds.suroot.com/UPLOAD.php